"""
TazoSploit SaaS v2 - Report Generator
Generates executive summaries and detailed reports
"""

import logging
from typing import Dict, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)

class ReportGenerator:
    """Service for generating security reports"""
    
    @staticmethod
    def generate_executive_summary(
        job: Dict,
        findings: List[Dict],
        risk_score: Dict
    ) -> str:
        """
        Generate AI-powered executive summary
        
        Returns markdown-formatted executive summary
        """
        
        # Build summary
        summary = f"""# Executive Summary

## Assessment Overview
**Target:** {', '.join(job.get('targets', []))}  
**Assessment Date:** {job.get('created_at', datetime.utcnow()).strftime('%B %d, %Y')}  
**Phase:** {job.get('phase', 'N/A')}  
**Duration:** {ReportGenerator._format_duration(job)}

## Risk Assessment

### Overall Risk Score: {risk_score['overall_score']}/100
**Risk Level:** {risk_score['risk_level'].upper()}

"""
        
        # Risk breakdown
        summary += f"""
| Component | Score | Status |
|-----------|-------|--------|
| Attack Surface | {risk_score['attack_surface_score']}/100 | {ReportGenerator._get_status_emoji(risk_score['attack_surface_score'])} |
| Exploitability | {risk_score['exploitability_score']}/100 | {ReportGenerator._get_status_emoji(risk_score['exploitability_score'])} |
| Impact | {risk_score['impact_score']}/100 | {ReportGenerator._get_status_emoji(risk_score['impact_score'])} |

"""
        
        # Findings summary
        severity = risk_score['severity_breakdown']
        summary += f"""## Findings Summary

**Total Findings:** {risk_score['total_findings']}

| Severity | Count |
|----------|-------|
| 🔴 Critical | {severity['critical']} |
| 🟠 High | {severity['high']} |
| 🟡 Medium | {severity['medium']} |
| 🔵 Low | {severity['low']} |
| ⚪ Info | {severity['info']} |

"""
        
        # Key findings
        critical_findings = [f for f in findings if f.get('severity') == 'critical']
        if critical_findings:
            summary += "## Critical Findings\n\n"
            for i, finding in enumerate(critical_findings[:5], 1):
                summary += f"{i}. **{finding.get('title', 'Untitled')}**\n"
                summary += f"   - Target: `{finding.get('target', 'N/A')}`\n"
                if finding.get('cve_id'):
                    summary += f"   - CVE: {finding['cve_id']}\n"
                if finding.get('mitre_technique'):
                    summary += f"   - MITRE: {finding['mitre_technique']}\n"
                summary += "\n"
        
        # Recommendations
        from .risk_scoring_service import RiskScoringService
        recommendations = RiskScoringService.generate_recommendations(risk_score, findings)
        
        summary += "## Recommendations\n\n"
        for rec in recommendations:
            summary += f"- {rec}\n"
        
        summary += f"""
## Next Steps

1. **Immediate Actions:** Address all critical findings within 24-48 hours
2. **Short-term (1-2 weeks):** Remediate high-severity findings
3. **Medium-term (1 month):** Address medium-severity findings
4. **Ongoing:** Implement continuous monitoring and regular assessments

---
*Report generated by TazoSploit SaaS v2 on {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}*
"""
        
        return summary
    
    @staticmethod
    def generate_detailed_report(
        job: Dict,
        findings: List[Dict],
        risk_score: Dict,
        mitre_coverage: Optional[Dict] = None
    ) -> str:
        """Generate detailed technical report"""
        
        report = f"""# Detailed Security Assessment Report

## Assessment Information

**Job ID:** {job.get('id', 'N/A')}  
**Target(s):** {', '.join(job.get('targets', []))}  
**Phase:** {job.get('phase', 'N/A')}  
**Intensity:** {job.get('intensity', 'medium')}  
**Started:** {job.get('started_at', 'N/A')}  
**Completed:** {job.get('completed_at', 'N/A')}  
**Duration:** {ReportGenerator._format_duration(job)}

---

## Risk Assessment

### Overall Risk Score: {risk_score['overall_score']}/100

**Risk Level:** {risk_score['risk_level'].upper()}

### Component Scores

- **Attack Surface:** {risk_score['attack_surface_score']}/100
  - Number of exposed services and endpoints
  - Target scope and complexity
  
- **Exploitability:** {risk_score['exploitability_score']}/100
  - Presence of known CVEs
  - Availability of public exploits
  - Complexity of exploitation
  
- **Impact:** {risk_score['impact_score']}/100
  - Severity of identified vulnerabilities
  - Potential business impact
  - Data exposure risk

---

## Findings Details

"""
        
        # Group findings by severity
        for severity in ['critical', 'high', 'medium', 'low', 'info']:
            severity_findings = [f for f in findings if f.get('severity') == severity]
            
            if severity_findings:
                report += f"### {severity.upper()} Severity ({len(severity_findings)})\n\n"
                
                for finding in severity_findings:
                    report += f"#### {finding.get('title', 'Untitled')}\n\n"
                    report += f"**Target:** `{finding.get('target', 'N/A')}`  \n"
                    report += f"**Type:** {finding.get('finding_type', 'N/A')}  \n"
                    
                    if finding.get('cve_id'):
                        report += f"**CVE:** {finding['cve_id']}  \n"
                    if finding.get('cwe_id'):
                        report += f"**CWE:** {finding['cwe_id']}  \n"
                    if finding.get('mitre_technique'):
                        report += f"**MITRE ATT&CK:** {finding['mitre_technique']}  \n"
                    
                    report += f"\n**Description:**\n{finding.get('description', 'No description')}\n\n"
                    
                    if finding.get('evidence'):
                        report += f"**Evidence:**\n```\n{finding['evidence'][:500]}\n```\n\n"
                    
                    if finding.get('remediation'):
                        report += f"**Remediation:**\n{finding['remediation']}\n\n"
                    
                    report += "---\n\n"
        
        # MITRE ATT&CK Coverage
        if mitre_coverage:
            report += "## MITRE ATT&CK Coverage\n\n"
            report += "Techniques identified during assessment:\n\n"
            
            techniques = mitre_coverage.get('techniques', [])
            for tech in techniques[:10]:
                report += f"- **{tech['id']}:** {tech['name']}\n"
            
            report += "\n"
        
        # Recommendations
        from .risk_scoring_service import RiskScoringService
        recommendations = RiskScoringService.generate_recommendations(risk_score, findings)
        
        report += "## Recommendations\n\n"
        for i, rec in enumerate(recommendations, 1):
            report += f"{i}. {rec}\n"
        
        report += f"""
---

## Appendix

### Methodology

This assessment was conducted using TazoSploit SaaS v2, an AI-powered penetration testing platform. The assessment followed industry-standard methodologies and the MITRE ATT&CK framework.

### Tools Used

The following tools were utilized during the assessment:
- Network scanning and enumeration
- Vulnerability scanning
- Exploitation frameworks
- Custom scripts and exploits

### Disclaimer

This report contains sensitive security information and should be treated as confidential. The findings represent the security posture at the time of assessment and may change over time.

---

*Report generated by TazoSploit SaaS v2*  
*Generated on: {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}*
"""
        
        return report
    
    @staticmethod
    def _format_duration(job: Dict) -> str:
        """Format job duration"""
        started = job.get('started_at')
        completed = job.get('completed_at')
        
        if not started or not completed:
            return "N/A"
        
        if isinstance(started, str):
            started = datetime.fromisoformat(started.replace('Z', '+00:00'))
        if isinstance(completed, str):
            completed = datetime.fromisoformat(completed.replace('Z', '+00:00'))
        
        duration = completed - started
        
        hours = duration.seconds // 3600
        minutes = (duration.seconds % 3600) // 60
        
        if hours > 0:
            return f"{hours}h {minutes}m"
        else:
            return f"{minutes}m"
    
    @staticmethod
    def _get_status_emoji(score: int) -> str:
        """Get status emoji based on score"""
        if score >= 80:
            return "🔴 Critical"
        elif score >= 60:
            return "🟠 High"
        elif score >= 40:
            return "🟡 Medium"
        else:
            return "🟢 Low"
    
    @staticmethod
    def generate_html_report(
        job: Dict,
        findings: List[Dict],
        risk_score: Dict,
        executive_summary: str,
        detailed_report: str
    ) -> str:
        """Generate HTML report with styling"""
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Assessment Report - {job.get('name', 'Untitled')}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
        }}
        .risk-score {{
            font-size: 48px;
            font-weight: bold;
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }}
        .risk-critical {{ background: #e74c3c; color: white; }}
        .risk-high {{ background: #e67e22; color: white; }}
        .risk-medium {{ background: #f39c12; color: white; }}
        .risk-low {{ background: #27ae60; color: white; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background: #3498db;
            color: white;
        }}
        .finding {{
            background: #f8f9fa;
            padding: 15px;
            margin: 15px 0;
            border-left: 4px solid #3498db;
            border-radius: 4px;
        }}
        .severity-critical {{ border-left-color: #e74c3c; }}
        .severity-high {{ border-left-color: #e67e22; }}
        .severity-medium {{ border-left-color: #f39c12; }}
        .severity-low {{ border-left-color: #3498db; }}
        code {{
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }}
        pre {{
            background: #2c3e50;
            color: #ecf0f1;
            padding: 15px;
            border-radius: 4px;
            overflow-x: auto;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #7f8c8d;
            font-size: 14px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Security Assessment Report</h1>
        <p><strong>Generated:</strong> {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}</p>
        
        <div class="risk-score risk-{risk_score['risk_level']}">
            Risk Score: {risk_score['overall_score']}/100
            <div style="font-size: 18px; margin-top: 10px;">
                {risk_score['risk_level'].upper()} RISK
            </div>
        </div>
        
        <div id="executive-summary">
            {ReportGenerator._markdown_to_html(executive_summary)}
        </div>
        
        <hr style="margin: 40px 0;">
        
        <div id="detailed-report">
            {ReportGenerator._markdown_to_html(detailed_report)}
        </div>
        
        <div class="footer">
            <p>This report was generated by TazoSploit SaaS v2</p>
            <p>© {datetime.utcnow().year} - Confidential Security Assessment</p>
        </div>
    </div>
</body>
</html>"""
        
        return html
    
    @staticmethod
    def _markdown_to_html(markdown: str) -> str:
        """Simple markdown to HTML conversion"""
        # This is a basic implementation - in production, use a proper markdown library
        html = markdown
        
        # Headers
        html = html.replace('### ', '<h3>').replace('\n\n', '</h3>\n\n')
        html = html.replace('## ', '<h2>').replace('\n\n', '</h2>\n\n')
        html = html.replace('# ', '<h1>').replace('\n\n', '</h1>\n\n')
        
        # Bold
        import re
        html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', html)
        
        # Code blocks
        html = re.sub(r'`([^`]+)`', r'<code>\1</code>', html)
        
        # Line breaks
        html = html.replace('\n\n', '<br><br>')
        
        return html
